eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
#    使用rabbitmq传输链路数据
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service

